### ISSUE TITLE
 \version "2.22.1"

### ISSUE THREAD

**Issue by tpapp** [jawatson/lilypond-harmonica#2]
Is Lilypond 2.22.1 really required for some feature, or would 2.22.0 or even lower be sufficient? I am asking because a lot of Linux distributions have older versions (eg Ubuntu 21.04 has 2.22, Debian stable has 2.19).

FWIW, the files in the repo render just fine with 2.22.0.

**Comment by jawatson** [comment]
Thanks for letting me know about this.  I've set require to 2.22.0.
